# escape=`
FROM plugins/buildx:windows-ltsc2022-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GCR" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/buildx-gcr.exe C:/bin/buildx-gcr.exe
ENTRYPOINT [ "C:\\bin\\buildx-gcr.exe" ]